server:
  port: 8888

spring:
  application:
    name: eduSystem
  datasource:
    driver-class-name: com.mysql.jdbc.Driver            # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.80.74:3306/edu_system?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wlhroot

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.wlh.springcloud.entity    # 所有Entity别名类所在包
